### ISSUE TITLE
Create an opencollective.com fund in order to facilitate open source sponsoring

### ISSUE THREAD

**Issue by darkdragon-001** [it-at-m/opensource.muenchen.de#78]
Create an [Open Collective Fund](https://docs.opencollective.com/help/financial-contributors/organizations/funds) in order to facilitate open source sponsoring. This gives these activities more visibility across the open source ecosystem. One can search for [existing funds](https://opencollective.com/search?q=&type=FUND) to see examples of other bigger sponsors.

**Comment by darkdragon-001** [comment]
I can also recommend https://backyourstack.com/it-at-m which lists all dependencies which are looking for funding at opencollective.com .

**Comment by klml** [comment]
@darkdragon-001 we already have an account https://opencollective.com/itm , but i forgot to mention it on [improve sponsoring](https://opensource.muenchen.de/de/improve.html#sponsoring). thanks for the hint, i added it 😄 

At the moment there is only our one global sponsoring: Vuetify, but of course opencollective is great for us because we can sponsor so easily and transparently further sponsoring from the  City Council resolution.

**Comment by darkdragon-001** [comment]
Oh this is awesome 😍 Also thanks for linking it on the page!

If sponsoring directly from the account works well enough then there is no need for a fund within that account.

Keep going with your great work for open source. I will closely follow 😉
